### PR TITLE
Added SURVEY_RUNNER_SCHEMA_URL to launcher variables

### PR DESCRIPTION
**Pull request by jonnyshaw89**

### CODE REVIEW

**Review by benhowes — CHANGES_REQUESTED** [review]
Might be me, but it doesn't seem to be using the new variable locally, I see 

```
eq-survey-launcher_1         | 2018/08/08 11:24:00 Loading metadata from schema: http://localhost:5000/schema/mbs/0823
eq-survey-launcher_1         | 2018/08/08 11:24:00 Metadata: []
``` 

in the logs

**Comment by jonnyshaw89** [comment]
@benhowes Seems to work for me. did you `docker-compose pull`?
```
eq-survey-launcher_1         | 2018/08/08 11:55:32 Survey Runner Schema URL: http://eq-survey-runner:5000
```

**Review by dwyeradam — APPROVED** [review]
Works for me.

**Review by benhowes — APPROVED** [review]

**Comment by benhowes** [comment]
Ah yes, all fine now!

**Comment by benhowes** [comment]
I was running a fresh clone, however a `docker-compose pull` did resolve the issue. Thanks!

**Pull request merged**
